version: '3'
services:
    kavanode:
        image: "kava/kava:earn-eip712-liquid-54c0b62"
        ports:
            # open default kava rpc port
            - "26657:26657"
            # open rest port
            - "1317:1317"
            # open grpc port
            - "9090:9090"
            # open grpc-web port
            - "9091:9091"
            # open EVM JSON-RPC port
            - "8545:8545"
            # open Eth websocket port
            - "8546:8546"
        volumes:
            - "./kava/initstate/.kava/config:/root/.kava/config"
            - "./kava/initstate/.kava/keyring-test/:/root/.kava/keyring-test"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command:
            - "sh"
            - "-c"
            - "/root/.kava/config/init-data-directory.sh && kava start --rpc.laddr=tcp://0.0.0.0:26657"
