
services:
    kavanode:
        image: kava/kava:${KAVA_TAG:-v0.10.0}
        ports:
            # open default kava rpc port
            - "26657:26657"
        volumes:
            - "./kava/initstate/.kvd/config:/root/.kvd/config"
        # start the blockchain, and set rpc to listen to connections from outside the container
        command: ["sh", "-c", "/root/.kvd/config/init-data-directory.sh && kvd start --pruning=nothing --rpc.laddr=tcp://0.0.0.0:26657"]
    kavarest:
        image: "kava/kava:${KAVA_TAG:-v0.10.0}"
        ports:
            # open default rest port
            - "1317:1317"
        command: ["kvcli", "rest-server", "--node=tcp://kavanode:26657", "--trust-node", "--laddr=tcp://0.0.0.0:1317"]
